---
- hosts: master
  strategy: debug
  roles:
    - name: TieredVPC
      TieredVPC_cidr: "{{ vpc_cidr }}"
      TieredVPC_tiers: "{{ vpc_layout }}"
      stack_name: "{{ lookup('stack_name', 'vpc') }}"
  post_tasks:
    - name: cloudformation
      cloudformation_info: { 'stack_name': "{{ lookup('stack_name', 'vpc') }}", 'region': "{{ region }}" }
      register: cf_vpc
    - set_fact:
        vpc:  "{{ cf_vpc['cloudformation'][lookup('stack_name', 'vpc')]['stack_outputs'] }}"
  tags: ['vpc']

- hosts: master
  strategy: debug
  roles:
    - name: "single-instance"
      instance: "{{ public_inst }}"
      subnet_id: "{{ vpc.PublicSubnetList.split(',')|first }}"
      stack_name: "{{ lookup('stack_name', 'bastion') }}"

    - name: "single-instance"
      instance: "{{ private_inst }}"
      subnet_id: "{{ vpc.PrivateSubnetList.split(',')|first }}"
      stack_name: "{{ lookup('stack_name', 'app') }}"
  tags: ['ec2', 'public']

