---
- hosts: master
  gather_facts: no
  pre_tasks:
    - debug: var=vpc_cidr
    - debug: var=vpc_layout
  roles:
    - name: TieredVPC
      TieredVPC_cidr: "{{ vpc_cidr }}"
      TieredVPC_tiers: "{{ vpc_layout }}"

- hosts: master
  gather_facts: no
  roles:
    - name: "single-instance"
      instance: "{{ public_inst }}"


