---
region: "eu-west-1"

vpc_cidr: "192.168.0.0/16"
vpc_layout:
  - name: Public
    public: yes
    nat_gateway: yes
    subnets:
      - "{{ vpc_cidr|ipsubnet(24, 0) }}"
      - "{{ vpc_cidr|ipsubnet(24, 2) }}"
      - "{{ vpc_cidr|ipsubnet(24, 4) }}"
  - name: Private
    nat_from: Public
    subnets:
      - "{{ vpc_cidr|ipsubnet(24, 1) }}"
      - "{{ vpc_cidr|ipsubnet(24, 3) }}"
      - "{{ vpc_cidr|ipsubnet(24, 5) }}"



public_inst:
  name: PublicInst
  image_id: ami-0ea3405d2d2522162
  keypair:
  instance_type: t2.micro
  security_groups:
  key_name: "nassim"

private_inst:
  name: PrivateInst
  image_id: ami-0ea3405d2d2522162
  keypair:
  instance_type: t2.micro
  security_groups:
  key_name: "nassim"


ssh_public_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDMF0QR0+ICw6cqTiNSO4R78WjZwWNK0MAj0Sv+Eyy5QYjyIj35Nb2Zo7yG9UmShJLHqdd3qejQNxFfTcMybProoyoOMqrjCA7xsZmJyhpgCj4CUBsSZ18d1CoEXcbw5lHvDiFcnoObhVjsEH38j5RjsP7a/KB1Hz17WAaC14ws0uu2TeGjqL8QAulW/QmX3ZCxYvQwxA4ETrgP0f4gbeA+uIDq5XBsDZJ1uu/puDUduuqZeB3WSE/HZiZxmqw2DaHdHLFDuyR16tvZgxUrkaLE/a2gk+BovpLkfLi93Bhb/IoJ70PSmXom8hjuyda55kStjCnirnt6yvf9SzlCIOt"
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDJjKzWpClG/m8AeWX1hibjuFSaEDKtNQvsVmsMr9itWLUN24V7Y54Y6rAu+1NPWY9eDSVE4Agkk6k7GIwuX00W8FIhY4PIUmyGL4LQCbY8Yr0ne+8dYpn+ZowWXGcdTI5Mmd5wHNCIjyn6qqhZXgOTXc3/hSJ1Cbts7zm8Ldj8HrJ9jtdRMtbJjQTFXfrzsyLVeraRImDTv3v6jk3uc9Qf8xaxOL/rkPMlXNt7Q3McNdzbWJ0zXLFtUurxTUiLWKMHRadvPLKFCc35hW/ck1+c/TqoK/6I4oaNFeR7hmJ99sdr2DGgjhFviJibdD/UpcicDTDrODu2Z1TqyHAIPt2t nacim@Oisins-MacBook-Pro.local"


