---
- name: Render cloudformation template.
  template:
    src: "cfn.template.j2"
    dest: ".generated_templates/{{ stack_name }}-cfn.template"
    force: yes

- name: Create the cloudformation stack.
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ stack_region }}"
    template: .generated_templates/{{ stack_name }}-cfn.template
    template_parameters:
      SubnetId: "{{ subnet_id }}"
  args:
    tags: "{{ stack_tags }}"
