---
# defaults file for TieredVPC

TieredVPC_prefix: "{{ ansible_env|default('') }}-{{ ansible_app|default('') }}-"
TieredVPC_name: "vpc"
TieredVPC_stack_name: "{{ TieredVPC_prefix }}{{ TieredVPC_name|lower }}"
TieredVPC_region: "{{ region }}"
TieredVPC_tags: {}

# main options
#TieredVPC_cidr: 192.168.0.0/16
#TieredVPC_tiers:
#  - name: One
#    public: yes
#    subnets:
#      - "{{ TieredVPC_cidr }}"
